name: Gradle Package

on:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Gradle
        run: gradle shadowJar

      - name: Publish release artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/awt-altgr-patch.jar